name: Fly Deploy
on: [push, workflow_dispatch]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  ENV_FILE: ${{ secrets.ENV_FILE }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          echo "$ENV_FILE" > .env
        shell: bash
      - run: flyctl deploy --remote-only
